name: Deploy to Server

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # STEP 1: Install Docker on server
      - name: Setup Docker on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SERVER_HOST }}
          username: ${{ secrets.EC2_SERVER_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y docker.io docker-compose-plugin
            sudo systemctl start docker
            sudo systemctl enable docker

            mkdir -p ~/devops

      # STEP 2: Copy docker-compose.yml
      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_SERVER_HOST }}
          username: ${{ secrets.EC2_SERVER_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/devops"

      # STEP 3: Deploy application
      - name: Deploy application on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SERVER_HOST }}
          username: ${{ secrets.EC2_SERVER_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            export DOCKER_TAG=${{ github.sha }}

            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            cd ~/devops

            docker pull $DOCKERHUB_USERNAME/my-app:$DOCKER_TAG

            docker-compose down
            docker-compose up -d --force-recreate
