name: Final Pipeline

on:
  workflow_dispatch: 

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml

  dependencies-scan:
    uses: ./.github/workflows/dependencies-scan.yml

  docker-linter:
    uses: ./.github/workflows/docker-linter.yml

  build-and-push:
    needs: [code-quality, secret-scan, dependencies-scan, docker-linter]
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets: inherit

  image-scan:
    needs: build-and-push
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit

  deploy:
    needs: image-scan
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
